install:
	npm ci

lint:
	npm run lint

lint-fix:
	npm run lint:fix

typecheck:
	npm run typecheck

dev:
	npm run dev

build:
	npm run build

start:
	npm run start

docker-dependencies-fix:
	docker run --rm -it -v .:/app -w /app node:22-alpine sh -c "npm i"