services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/:/app
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
    command: npm run dev

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend/:/app

  db:
    ports:
      - "5432:5432"
