name: Build, Push and Deploy

on:
  push:
    branches: ["main"]

jobs:
  generate-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache API generation
        id: cache-api
        uses: actions/cache@v4
        with:
          path: ./api/dist
          key: ${{ runner.os }}-api-${{ hashFiles('api/main.tsp') }}
          restore-keys: |
            ${{ runner.os }}-api-

      - name: Generate API files
        if: steps.cache-api.outputs.cache-hit != 'true'
        run: make gen-all

      - name: Upload generated client
        uses: actions/upload-artifact@v4
        with:
          name: generated-client
          path: ./api/dist/client
          retention-days: 1

      - name: Upload generated backend
        uses: actions/upload-artifact@v4
        with:
          name: generated-backend
          path: ./api/dist/server
          retention-days: 1

  build-push-and-deploy:
    needs: generate-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download generated client
        uses: actions/download-artifact@v4
        with:
          name: generated-client
          path: ./api/dist/client

      - name: Download generated backend
        uses: actions/download-artifact@v4
        with:
          name: generated-backend
          path: ./api/dist/server

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
